### ISSUE TITLE
Last field margin, label border and validator

### ISSUE THREAD

**Issue by evyasonov** [yarbshk/vue-formly-buefy#2]
Hi! I created a toy form based on input example ( https://yarbshk.github.io/vue-formly-buefy-examples/#input ). Code is below.  And I have unexpected behavior :
 - email field has margin-bottom, while test field don't have margin-bottom. That's why registration bottom  don't have any margin. In the example all the fields have margin-bottom. 
 - fieldset has a border, but in the example there's no border
 - email validator don't work as in example

Can you please help with it

Thanks in advance

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/buefy/lib/buefy.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.0/css/bulma.min.css">
</head>
<body>
    <div id="myVue">
        <h1>my sign in form</h1>
        <sign-in-form></sign-in-form>
    </div>

    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.js"></script>
    <script src="https://unpkg.com/buefy"></script>
    <script src="vue-formly.min.js"></script>
    <script src="vue-formly-buefy.min.js"></script>
    <script src="vue-formly-buefy-controls.min.js"></script>

    <script>
        Vue.use(Buefy.default, {defaultIconPack: 'fas'});
        Vue.use(VueFormly);
        Vue.use(VueFormlyBuefy);


    Vue.component('sign-in-form', {
        data: function () {
            return {
                action: '/sign/in',
                method: 'post',
                form: {},
                model: {
                    email: '',
                    test: ''
                },
                fields: [
                    {
                        "key": "email",
                        "type": "input-with-field",
                        "required": true,
                        "templateOptions": {
                            "properties": {
                                "type": "email",
                                "required": true,
                                "placeholder": 'email@example.com',
                                "icon": "envelope",
                            },
                        },
                        "validators": {
                            "format": {
                                "message": "The email address doesn't match the pattern"
                            }
                        }
                    },
                    {
                        "key": "test",
                        "type": "input-with-field",
                        "required": true,
                        "templateOptions": {
                            "properties": {
                                "type": "email",
                                "required": true,
                                "placeholder": 'email@example.com',
                                "icon": "envelope",
                            },
                        },
                        "validators": {
                            "format": {
                                "message": "The email address doesn't match the pattern"
                            }
                        }
                    },
                ]
            }
        },
        template: `
            <form @submit.prevent="handleSubmission" >
                <formly-form :form="form" :model="model" :fields="fields"></formly-form>
                <b-field>
                    <p class="control">
                        <button class="button is-link">Register</button>
                    </p>
                </b-field>
            </form>
        `,
        methods: {
            handleSubmission: function () {
                alert("test")
            }
        },

    })


    new Vue({
        el: '#myVue',
    });

    </script>
</body>
</html>
```

**Comment by yarbshk** [comment]
hi @evyasonov... firstly i would ask you to use this issue tracker for bug reports that are relative to vue-formly-buefy (next i'll use "the plugin") directly (please see detail explanation below)...

the plugin is just a superstructure under the [vue-formly](https://matt-sanders.gitbooks.io/vue-formly/content/v/2.0/) and [buefy](https://buefy.github.io/#/documentation/start) packages.. so before asking a question please make sure that you understood how the packages actually works by reading its documentation (see links above) and whether the packages don't contain any bugs... then please make sure again that it's actually a bug rather than your misunderstanding. thanks!

**1-2) regarding to the styles.** the plugin doesn't use any CSS just minified JS.. so if you have any questions regarding CSS please ask ones to the authors of the [bulma](https://bulma.io/) or [buefy](https://buefy.github.io/#/) packages... however [the plugin examples](https://github.com/yarbshk/vue-formly-buefy-examples/) are using some custom styles (such as [global](https://github.com/yarbshk/vue-formly-buefy-examples/blob/master/src/scss/index.scss) and [embedded](https://github.com/yarbshk/vue-formly-buefy-examples/blob/master/src/components/forms/InputForm.vue#L169) ones) and you can use it too. it's a reason why you're seeing fieldset borders and inappropriate margins.

**3) regarding to the validator.** you make a mistake while declaring the validator and hence you had got an unpredictable result... an _expression_ property is required for a validator but you provided only a _message_ one... so if you want to use a validator you should [declare a rule](https://matt-sanders.gitbooks.io/vue-formly/content/v/2.0/how_to_use/validation.html) (called expression) to explicitly specify behavior of the validator as shown in the following example:

```javascript
"validators": {
    "format": {
        "expression": function (field, model, next) {
            next(/^[\w.\-]+@[\w.\-]+\.[a-z]+$/.test(model[field.key]))
        },
        "message": "The email address doesn't match the pattern"
    }
}
```

hope it helps! i close the issue :)

**Comment by evyasonov** [comment]
@yarbshk 
Got it! Thank you very much for detailed answers! The third one hepled
